import React from 'react'
import styled from 'styled-components'
import { useDraggableWithDestination } from '../../lib/hooks/useDraggableWithDestination'
import { Vector } from '../../lib/types'

const Object = styled.div`
  width: 100px;
  height: 100px;
  background: blue;
`

const Page: React.FC = () => {
  const [destination, setDestination] = React.useState<Vector>({ x: 0, y: 0 })

  const { drag, position, ref } = useDraggableWithDestination(destination, [
    destination,
  ])

  return (
    <>
      <h1>dsafdsfadf</h1>
      <Object
        ref={ref}
        style={{
          transform: `translate3d(${position.x}px, ${position.y}px, 0px)`,
          cursor: drag ? 'grabbing' : 'grab',
        }}
      />
      <button
        onClick={() => setDestination((v) => ({ x: v.x + 50, y: v.y + 50 }))}
      >
        dfadsaf
      </button>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
      <p>dafdafdsfads</p>
    </>
  )
}

export default Page
